# Generated by Django 5.1.1 on 2024-10-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol_app', '0003_event_date_alter_volunteer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
