# Generated by Django 5.1.1 on 2024-10-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vol_app', '0004_remove_volunteer_user_volunteer_email_volunteer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
